/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package andregame;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class GameGUI extends javax.swing.JFrame {
    GamePopulation gpop = GamePopulation.getInstance();
    GameEngine engine;
    int score;
    
    
        
    /**
     * Creates new form GameGUI
     */
    public GameGUI() {
        initComponents();
        inputBox.setVisible(false);
        messageArea.setVisible(false);
        scoreLBL.setVisible(false);
        showQuestion.setVisible(false);
        submitBTN.setVisible(false);
        messageAreaText.setVisible(false);
        nameTF.setVisible(false);
        submitNameBTN.setVisible(false);
        nextBTN.setVisible(false);
        
        engine = new GameEngine();
        score = engine.getScore();
        
        //Some items are hidden for a cleaner GUI
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBTN = new javax.swing.JButton();
        showQuestion = new javax.swing.JLabel();
        inputBox = new javax.swing.JTextField();
        submitBTN = new javax.swing.JButton();
        scoreLBL = new javax.swing.JLabel();
        messageArea = new javax.swing.JScrollPane();
        messageAreaText = new javax.swing.JTextArea();
        instructionsTA = new javax.swing.JScrollPane();
        instructionsTAtext = new javax.swing.JTextArea();
        gameStartBTN = new javax.swing.JButton();
        nameTF = new javax.swing.JTextField();
        submitNameBTN = new javax.swing.JButton();
        currentScoreLBL = new javax.swing.JLabel();
        nextBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(691, 360));
        setPreferredSize(new java.awt.Dimension(691, 360));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        backBTN.setForeground(new java.awt.Color(255, 51, 51));
        backBTN.setText("Exit");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        getContentPane().add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 90, 40));

        showQuestion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        showQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showQuestion.setText("Question example: What is the carbon footprint of the average adult? per year?");
        getContentPane().add(showQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 680, -1));

        inputBox.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        inputBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBoxActionPerformed(evt);
            }
        });
        getContentPane().add(inputBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 182, 46));

        submitBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        submitBTN.setText("Submit");
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(submitBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 154, 48));

        scoreLBL.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        scoreLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLBL.setText("Your score was 10/10 congrats!");
        getContentPane().add(scoreLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 130, 680, -1));

        messageAreaText.setColumns(20);
        messageAreaText.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        messageAreaText.setLineWrap(true);
        messageAreaText.setRows(5);
        messageArea.setViewportView(messageAreaText);

        getContentPane().add(messageArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 680, 119));

        instructionsTAtext.setColumns(20);
        instructionsTAtext.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        instructionsTAtext.setRows(5);
        instructionsTAtext.setText("Instructions: \nFirst, read the question carefully.\nSecond, try to guess a value, the range is between 0 and 100 kg. \nThird, click the submit button and see the results!\n");
        instructionsTA.setViewportView(instructionsTAtext);

        getContentPane().add(instructionsTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 680, 110));

        gameStartBTN.setBackground(new java.awt.Color(255, 51, 51));
        gameStartBTN.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        gameStartBTN.setForeground(new java.awt.Color(255, 255, 255));
        gameStartBTN.setText("START GAME!");
        gameStartBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameStartBTNActionPerformed(evt);
            }
        });
        getContentPane().add(gameStartBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 185, 47));

        nameTF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        getContentPane().add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 170, 40));

        submitNameBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        submitNameBTN.setText("Submit name");
        submitNameBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitNameBTNActionPerformed(evt);
            }
        });
        getContentPane().add(submitNameBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 160, 40));

        currentScoreLBL.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        currentScoreLBL.setText("Score: 0");
        getContentPane().add(currentScoreLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        nextBTN.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        nextBTN.setText("Next ");
        nextBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBTNActionPerformed(evt);
            }
        });
        getContentPane().add(nextBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 160, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gameStartBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameStartBTNActionPerformed
        // TODO add your handling code here:
        inputBox.setVisible(true);
        messageArea.setVisible(true);
        scoreLBL.setVisible(false);
        showQuestion.setVisible(true);
        submitBTN.setVisible(true);
        messageAreaText.setVisible(true);
        gameStartBTN.setVisible(false);
        instructionsTA.setVisible(false);
        instructionsTAtext.setVisible(false);
        messageAreaText.setText("");
        showQuestion.setText(engine.getNextQuestion());
    }//GEN-LAST:event_gameStartBTNActionPerformed

    private void inputBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBoxActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
//        CleanEnergyGUI mainGUI = new CleanEnergyGUI(); 
//        mainGUI.setVisible(true); 
//        this.setVisible(false); 
//        this.dispose();
        System.exit(1);
        //RETRUN TO BACK BUTTON STATE AFTER REFACTOR


//UN-COMMENT PART WHEN REFACTORED TO MAIN PROJECT.
    }//GEN-LAST:event_backBTNActionPerformed

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        // TODO add your handling code here:
        String input = inputBox.getText();
        
        //When an answer is submitted, it tries to parse it to an int
        //otherwise it returns an error message and does not proceeds to the next level.
        try {
            int value = Integer.parseInt(input);
            String feedBack = engine.submitAnswer(value);
            if(score != engine.getScore()){
                
                messageArea.setBackground(Color.green);
                score++;
                currentScoreLBL.setText("Score: "+ score);
            }else{
                messageArea.setBackground(Color.red);
            }
            messageAreaText.setText(feedBack);
            nextBTN.setVisible(true);
            inputBox.setVisible(false);
            submitBTN.setVisible(false);
            

                
            
            
            
        } catch (NumberFormatException ex) {
            messageAreaText.setText("Invalid input! Please enter an integer.");
        }
        
        
    }//GEN-LAST:event_submitBTNActionPerformed

    private void submitNameBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitNameBTNActionPerformed
        // TODO add your handling code here:
        String name = nameTF.getText();
        engine.addUser(name, score);
        String highScores = engine.getHighScore();
        JOptionPane.showMessageDialog(null, highScores);
        System.exit(1);

    }//GEN-LAST:event_submitNameBTNActionPerformed

    private void nextBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBTNActionPerformed
        // TODO add your handling code here:
        showQuestion.setText(engine.getNextQuestion());
        messageAreaText.setText("");
        nextBTN.setVisible(false);
                    //To do whenever the game has been finished
        if(engine.isQuizOver()){
            inputBox.setVisible(false);
            scoreLBL.setVisible(true);
            showQuestion.setVisible(true);
            submitBTN.setVisible(false);
            nameTF.setVisible(true);
            submitNameBTN.setVisible(true);
            messageArea.setVisible(false);
            currentScoreLBL.setVisible(false);
            scoreLBL.setText("Your final score was: "+ engine.getScore());
            backBTN.setVisible(false);
        }else{
            inputBox.setVisible(true);
            submitBTN.setVisible(true);
        }
       
    }//GEN-LAST:event_nextBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameGUI().setVisible(true);
            }
        });
  
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel currentScoreLBL;
    private javax.swing.JButton gameStartBTN;
    private javax.swing.JTextField inputBox;
    private javax.swing.JScrollPane instructionsTA;
    private javax.swing.JTextArea instructionsTAtext;
    private javax.swing.JScrollPane messageArea;
    private javax.swing.JTextArea messageAreaText;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton nextBTN;
    private javax.swing.JLabel scoreLBL;
    private javax.swing.JLabel showQuestion;
    private javax.swing.JButton submitBTN;
    private javax.swing.JButton submitNameBTN;
    // End of variables declaration//GEN-END:variables
}
